#!/bin/bash
PORT="$1"
stty -F "$PORT" 57600
shift
while [ ! -z "$2" ]
do
  if awk -vchan="$2" -f "$0.awk" "$1" "$0.dat" >/tmp/wave$$
  then
     while read -r line 
     do
        echo -n . 
        echo "$line" >"$PORT"
	sleep 1
     done </tmp/wave$$
     echo "$1 done"
  else
    echo "$1 failed"
  fi
  shift
  shift
done


